apiVersion: batch/v1
kind: Job
metadata:
  name: ea-nunit
spec:
  template:
    spec:
      containers:
      - name: nunit-container
        image: ajovano/ea-nunit
      restartPolicy: Never
  backoffLimit: 1
